- hosts: localhost
  become: no
  gather_facts: no
  vars:
    smatrix_template_src: "{{ item.template_file.source }}"
    smatrix_dimensions:
      template_file:
        - source: io500.sh.j2
        - source: config.ini.j2
      nodes: [1]
      ntasks_per_node: [2]
      filesystem:
        - name: pansas
          mountpoint: /work/scratch-pw2/
        - name: quobyte
          mountpoint: /work/scratch-nopw/
        - name: pure
          mountpoint: /work/stackhpc-pure/
      stonewall: [1]
    smatrix_template_dest_dir: sbatch
    smatrix_template_suffix: ".{{ [item.nodes, item.ntasks_per_node, item.filesystem.name] | join('-') }}" # don't want template_file in there
    smatrix_submit_when: "item.template_file.source != 'config.ini.j2'"

  tasks:
    - name: Run test matrix
      import_role:
        name: stackhpc.smatrix
