- hosts: localhost
  become: no
  gather_facts: no
  vars:
    smatrix_template_src: "{{ item.template_file }}"
    smatrix_dimensions:
      template_file:
        - io500.sh.j2
        - config.ini.j2
      nodes: [1]
      ntasks_per_node: [2]
      filesystem:
        - name: pansas
          mountpoint: /work/scratch-pw2/
        - name: quobyte
          mountpoint: /work/scratch-nopw/
        - name: pure
          mountpoint: /work/stackhpc-pure/
      stonewall: [1]
    smatrix_template_dest_dir: "results/{{ item.filesystem.name }}"
    smatrix_template_suffix: ".{{ [item.filesystem.name, item.nodes, item.ntasks_per_node] | join('-') }}" # don't want template_file in there
    smatrix_exclude_submit:
      - template_file: config.ini.j2

  tasks:
    - name: Run test matrix
      import_role:
        name: stackhpc.smatrix
