- hosts: localhost
  become: no
  gather_facts: no
  vars:
    smatrix_template_src: '*.j2'
    smatrix_dimensions:
      nodes: [1, 2]
      ntasks_per_node: [2, 8, 16]
      filesystem:
        # - name: pansas
        #   mountpoint: /gws/pw/j07/perf_testing/stackhpc
        # - name: quobyte
        #   mountpoint: /gws/nopw/j04/perf_testing/stackhpc
        - name: pure
          mountpoint: /work/stackhpc-pure/
      stonewall: [30, 300]
      iters: [0, 1, 2]
      time: ['2:0:0'] # job time, hours:minutes:seconds
      git_describe: [ "{{ smatrix_git_describe }}" ]
    run_description: "{{ timestamp }}.{{ item_idx }}"
    smatrix_template_suffix: ".{{ run_description }}"
    smatrix_template_dest_dir: "{{ lookup('env', 'PWD') }}/io500/runs/{{ run_description }}"
    smatrix_submit_src: "{{ smatrix_template_dest_dir }}/io500{{smatrix_template_suffix }}.sh"

  tasks:
    - name: Set timestamp for this play
      set_fact:
        timestamp: "{{ lookup('pipe','date -u +%Y%m%d.%H%M%S') }}"
      tags: always
    - name: Run test matrix
      import_role:
        name: stackhpc.smatrix
