- hosts: localhost
  become: no
  gather_facts: no
  vars:
    smatrix_template_src: '*.j2'
    smatrix_dimensions:
      nodes: [1]
      ntasks_per_node: [2]
      filesystem:
        - name: pansas
          mountpoint: /gws/pw/j07/perf_testing/stackhpc
        - name: quobyte
          mountpoint: /gws/nopw/j04/perf_testing/stackhpc
        - name: pure
          mountpoint: /work/stackhpc-pure/
      stonewall: [30]
      time: ['2:0:0'] # job time, hours:minutes:seconds
    run_description: "{{ [item.filesystem.name, item.nodes, item.ntasks_per_node] | join('-') }}" # only want fs.name
    smatrix_template_suffix: ".{{ run_description }}"
    smatrix_template_dest_dir: "{{ lookup('env', 'PWD') }}/io500/runs/{{ run_description }}"
    smatrix_submit_src: "{{ smatrix_template_dest_dir }}/io500{{smatrix_template_suffix }}.sh"

  tasks:
    - name: Run test matrix
      import_role:
        name: stackhpc.smatrix
