- hosts: localhost
  become: no
  gather_facts: no
  vars:
    smatrix_template_src: '*.j2'
    smatrix_dimensions:
      nodes: [1] #, 2, 10]
      ntasks_per_node: [1, 2, 4, 16]
      filesystem:
        - name: panasas
          mountpoint: /gws/pw/j07/perf_testing3 # exclusive use
        - name: quobyte
          mountpoint: /gws/nopw/j04/perf_testing3/stackhpc
        - name: pure
          mountpoint: /work/stackhpc-pure/
      stonewall: [300]
      iters: [0, 1, 2]
      time: ['4:0:0']
      ior_api: ['POSIX']
      # ior_api: ['MPIIO']
    run_description: "{{ [item.filesystem.name, item.nodes, item.ntasks_per_node, item.stonewall, item.iters, item.ior_api] | join('-') }}" # only want fs.name, don't want time, git_describe
    smatrix_template_suffix: ".{{ run_description }}"
    smatrix_template_dest_dir: "{{ lookup('env', 'PWD') }}/io500/runs/{{ run_description }}"
    smatrix_submit_src: "{{ smatrix_template_dest_dir }}/io500{{smatrix_template_suffix }}.sh"
    smatrix_output_path: "{{ smatrix_template_dest_dir }}/result_summary.txt"
    smatrix_exclude:
      # MPI on quobyte crashed the nodes
      - filesystem:
          name: quobyte
          mountpoint: /gws/nopw/j04/perf_testing3/stackhpc
        ior_api: 'MPIIO'

  tasks:
    - name: Run test matrix
      import_role:
        name: stackhpc.smatrix
