---

- hosts: localhost
  gather_facts: no

  vars:
    partition: stackhpc
    account: stackhpc
    creds: "{{ lookup('file', './creds.env') }}"
    max_job_time: "4:00:00"
    max_storage_capacity: 10TB
    smatrix_template_src: "s3-warp.sh.j2"
    smatrix_template_dest_dir: ./benchmark-runs
    smatrix_template_basename: s3
    smatrix_dimensions:
      storage: ["pure"]
      benchmark_type: ["put"]
      # nodes: [1, 2, 5]
      # threads_per_node: [1, 20, 50, 100]
      nodes: [2]
      threads_per_node: [50]
      objects_per_node: [0] # 'put' benchmarks only require a duration
      # obj_sizes: ["10KiB", "10MiB", "100MiB", "1GiB"]
      obj_sizes: ["1GiB"]
      duration: ['5m']

  tasks:
    - name: Run sanity checks
      import_tasks:
        file: sanity-checks.yml
    - name: Run object storage benchmarks
      import_role:
        name: smatrix